# Site settings
title: MCSC
email: mcsc@maine.edu
description: > # this means to ignore newlines until "baseurl:"
  The Maine Cyber Security Cluster (MCSC) is an academic and research center bringing together government, industry, and academia dedicated to workforce and economic development in the field of cyber security.
# baseurl: "/MCSC/" # the subpath of your site, e.g. /blog/
# url: "/MCSC/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
permalink: '/blog/:year/:title/'
relative_permalinks: false
paginate_path: '/blog/page:num/'
include: ['_pages']
future: true
